const timeout_interval = 100;
const characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.,;!?\"':-<>\n "
var is_break = false;
var current_speed = 5;
var input_interval = null;

const examples = [
    `
    NEL MEZZO DEL CAMMIN DI NOSTRA VITA
MI RITROVAI PER UNA SELVA OSCURA,
CHÉ LA DIRITTA VIA ERA SMARRITA.3

AHI QUANTO A DIR QUAL ERA È COSA DURA
ESTA SELVA SELVAGGIA E ASPRA E FORTE
CHE NEL PENSIER RINOVA LA PAURA!6

TANT’È AMARA CHE POCO È PIÙ MORTE;
MA PER TRATTAR DEL BEN CH’I’ VI TROVAI,
DIRÒ DE L’ALTRE COSE CH’I’ V’ HO SCORTE.9

IO NON SO BEN RIDIR COM’I’ V’INTRAI,
TANT’ERA PIEN DI SONNO A QUEL PUNTO
CHE LA VERACE VIA ABBANDONAI.12

MA POI CH’I’ FUI AL PIÈ D’UN COLLE GIUNTO,
LÀ DOVE TERMINAVA QUELLA VALLE
CHE M’AVEA DI PAURA IL COR COMPUNTO,15

GUARDAI IN ALTO E VIDI LE SUE SPALLE
VESTITE GIÀ DE’ RAGGI DEL PIANETA
CHE MENA DRITTO ALTRUI PER OGNE CALLE.18

ALLOR FU LA PAURA UN POCO QUETA,
CHE NEL LAGO DEL COR M’ERA DURATA
LA NOTTE CH’I’ PASSAI CON TANTA PIETA.21

E COME QUEI CHE CON LENA AFFANNATA,
USCITO FUOR DEL PELAGO A LA RIVA,
SI VOLGE A L’ACQUA PERIGLIOSA E GUATA,24

COSÌ L’ANIMO MIO, CH’ANCOR FUGGIVA,
SI VOLSE A RETRO A RIMIRAR LO PASSO
CHE NON LASCIÒ GIÀ MAI PERSONA VIVA.27

POI CH’ÈI POSATO UN POCO IL CORPO LASSO,
RIPRESI VIA PER LA PIAGGIA DISERTA,
SÌ CHE ’L PIÈ FERMO SEMPRE ERA ’L PIÙ BASSO.30

ED ECCO, QUASI AL COMINCIAR DE L'ERTA,
UNA LONZA LEGGERA E PRESTA MOLTO,
CHE DI PEL MACOLATO ERA COVERTA;33

E NON MI SI PARTIA DINANZI AL VOLTO,
ANZI ’MPEDIVA TANTO IL MIO CAMMINO,
CH’I’ FUI PER RITORNAR PIÙ VOLTE VÒLTO.36

TEMP’ERA DAL PRINCIPIO DEL MATTINO,
E ’L SOL MONTAVA ’N SÙ CON QUELLE STELLE
CH’ERAN CON LUI QUANDO L’AMOR DIVINO39

MOSSE DI PRIMA QUELLE COSE BELLE;
SÌ CH’A BENE SPERAR M’ERA CAGIONE
DI QUELLA FIERA A LA GAETTA PELLE42

L’ORA DEL TEMPO E LA DOLCE STAGIONE;
MA NON SÌ CHE PAURA NON MI DESSE
LA VISTA CHE M'APPARVE D'UN LEONE.45

QUESTI PAREA CHE CONTRA ME VENISSE
CON LA TEST’ALTA E CON RABBIOSA FAME,
SÌ CHE PAREA CHE L’AERE NE TREMESSE.48

ED UNA LUPA, CHE DI TUTTE BRAME
SEMBIAVA CARCA NE LA SUA MAGREZZA,
E MOLTE GENTI FÉ GIÀ VIVER GRAME,51

QUESTA MI PORSE TANTO DI GRAVEZZA
CON LA PAURA CH’USCIA DI SUA VISTA,
CH’IO PERDEI LA SPERANZA DE L’ALTEZZA.54

E QUAL È QUEI CHE VOLONTIERI ACQUISTA,
E GIUGNE ’L TEMPO CHE PERDER LO FACE,
CHE ’N TUTTI SUOI PENSIER PIANGE E S’ATTRISTA;57

TAL MI FECE LA BESTIA SANZA PACE,
CHE, VENENDOMI ’NCONTRO, A POCO A POCO
MI RIPIGNEVA LÀ DOVE ’L SOL TACE.60

MENTRE CH’I’ ROVINAVA IN BASSO LOCO,
DINANZI A LI OCCHI MI SI FU OFFERTO
CHI PER LUNGO SILENZIO PAREA FIOCO.63

QUANDO VIDI COSTUI NEL GRAN DISERTO,
"MISERERE DI ME", GRIDAI A LUI,
"QUAL CHE TU SII, OD OMBRA OD OMO CERTO!".66

RISPUOSEMI: "NON OMO, OMO GIÀ FUI,
E LI PARENTI MIEI FURON LOMBARDI,
MANTOANI PER PATRÏA AMBEDUI.69

NACQUI SUB IULIO, ANCOR CHE FOSSE TARDI,
E VISSI A ROMA SOTTO ’L BUONO AUGUSTO
NEL TEMPO DE LI DÈI FALSI E BUGIARDI.72

POETA FUI, E CANTAI DI QUEL GIUSTO
FIGLIUOL D’ANCHISE CHE VENNE DI TROIA,
POI CHE ’L SUPERBO ILÏÓN FU COMBUSTO.75

MA TU PERCHÉ RITORNI A TANTA NOIA?
PERCHÉ NON SALI IL DILETTOSO MONTE
CH’È PRINCIPIO E CAGION DI TUTTA GIOIA?".78

"OR SE’ TU QUEL VIRGILIO E QUELLA FONTE
CHE SPANDI DI PARLAR SÌ LARGO FIUME?",
RISPUOS’IO LUI CON VERGOGNOSA FRONTE.81

"O DE LI ALTRI POETI ONORE E LUME,
VAGLIAMI ’L LUNGO STUDIO E ’L GRANDE AMORE
CHE M’ HA FATTO CERCAR LO TUO VOLUME.84

TU SE’ LO MIO MAESTRO E ’L MIO AUTORE,
TU SE’ SOLO COLUI DA CU’ IO TOLSI
LO BELLO STILO CHE M’ HA FATTO ONORE.87

VEDI LA BESTIA PER CU’ IO MI VOLSI;
AIUTAMI DA LEI, FAMOSO SAGGIO,
CH’ELLA MI FA TREMAR LE VENE E I POLSI".90

"A TE CONVIEN TENERE ALTRO VÏAGGIO",
RISPUOSE, POI CHE LAGRIMAR MI VIDE,
"SE VUO’ CAMPAR D’ESTO LOCO SELVAGGIO;93

CHÉ QUESTA BESTIA, PER LA QUAL TU GRIDE,
NON LASCIA ALTRUI PASSAR PER LA SUA VIA,
MA TANTO LO ’MPEDISCE CHE L’UCCIDE;96

E HA NATURA SÌ MALVAGIA E RIA,
CHE MAI NON EMPIE LA BRAMOSA VOGLIA,
E DOPO ’L PASTO HA PIÙ FAME CHE PRIA.99

MOLTI SON LI ANIMALI A CUI S’AMMOGLIA,
E PIÙ SARANNO ANCORA, INFIN CHE ’L VELTRO
VERRÀ, CHE LA FARÀ MORIR CON DOGLIA.102

QUESTI NON CIBERÀ TERRA NÉ PELTRO,
MA SAPÏENZA, AMORE E VIRTUTE,
E SUA NAZION SARÀ TRA FELTRO E FELTRO.105

DI QUELLA UMILE ITALIA FIA SALUTE
PER CUI MORÌ LA VERGINE CAMMILLA,
EURIALO E TURNO E NISO DI FERUTE.108

QUESTI LA CACCERÀ PER OGNE VILLA,
FIN CHE L’AVRÀ RIMESSA NE LO ’NFERNO,
LÀ ONDE ’NVIDIA PRIMA DIPARTILLA.111

OND’IO PER LO TUO ME’ PENSO E DISCERNO
CHE TU MI SEGUI, E IO SARÒ TUA GUIDA,
E TRARROTTI DI QUI PER LOCO ETTERNO;114

OVE UDIRAI LE DISPERATE STRIDA,
VEDRAI LI ANTICHI SPIRITI DOLENTI,
CH’A LA SECONDA MORTE CIASCUN GRIDA;117

E VEDERAI COLOR CHE SON CONTENTI
NEL FOCO, PERCHÉ SPERAN DI VENIRE
QUANDO CHE SIA A LE BEATE GENTI.120

A LE QUAI POI SE TU VORRAI SALIRE,
ANIMA FIA A CIÒ PIÙ DI ME DEGNA:
CON LEI TI LASCERÒ NEL MIO PARTIRE;123

CHÉ QUELLO IMPERADOR CHE LÀ SÙ REGNA,
PERCH’I’ FU’ RIBELLANTE A LA SUA LEGGE,
NON VUOL CHE ’N SUA CITTÀ PER ME SI VEGNA.126

IN TUTTE PARTI IMPERA E QUIVI REGGE;
QUIVI È LA SUA CITTÀ E L’ALTO SEGGIO:
OH FELICE COLUI CU’ IVI ELEGGE!".129

E IO A LUI: "POETA, IO TI RICHEGGIO
PER QUELLO DIO CHE TU NON CONOSCESTI,
ACCIÒ CH’IO FUGGA QUESTO MALE E PEGGIO,132

CHE TU MI MENI LÀ DOV’OR DICESTI,
SÌ CH’IO VEGGIA LA PORTA DI SAN PIETRO
E COLOR CUI TU FAI COTANTO MESTI".135

ALLOR SI MOSSE, E IO LI TENNI DIETRO.`,

`OH ABBONDANTE GRAZIA OND’ IO PRESUNSI
FICCAR LO VISO PER LA LUCE ETTERNA,
TANTO CHE LA VEDUTA VI CONSUNSI!84

NEL SUO PROFONDO VIDI CHE S’INTERNA,
LEGATO CON AMORE IN UN VOLUME,
CIÒ CHE PER L’UNIVERSO SI SQUADERNA:87

SUSTANZE E ACCIDENTI E LOR COSTUME
QUASI CONFLATI INSIEME, PER TAL MODO
CHE CIÒ CH’I’ DICO È UN SEMPLICE LUME.90

LA FORMA UNIVERSAL DI QUESTO NODO
CREDO CH’I’ VIDI, PERCHÉ PIÙ DI LARGO,
DICENDO QUESTO, MI SENTO CH’I’ GODO.93

UN PUNTO SOLO M’È MAGGIOR LETARGO
CHE VENTICINQUE SECOLI A LA ’MPRESA
CHE FÉ NETTUNO AMMIRAR L’OMBRA D’ARGO.96

COSÌ LA MENTE MIA, TUTTA SOSPESA,
MIRAVA FISSA, IMMOBILE E ATTENTA,
E SEMPRE DI MIRAR FACEASI ACCESA.99

A QUELLA LUCE COTAL SI DIVENTA,
CHE VOLGERSI DA LEI PER ALTRO ASPETTO
È IMPOSSIBIL CHE MAI SI CONSENTA;102

PERÒ CHE ’L BEN, CH’È DEL VOLERE OBIETTO,
TUTTO S’ACCOGLIE IN LEI, E FUOR DI QUELLA
È DEFETTIVO CIÒ CH’È LÌ PERFETTO.105

OMAI SARÀ PIÙ CORTA MIA FAVELLA,
PUR A QUEL CH’IO RICORDO, CHE D’UN FANTE
CHE BAGNI ANCOR LA LINGUA A LA MAMMELLA.108

NON PERCHÉ PIÙ CH’UN SEMPLICE SEMBIANTE
FOSSE NEL VIVO LUME CH’IO MIRAVA,
CHE TAL È SEMPRE QUAL S’ERA DAVANTE;111

MA PER LA VISTA CHE S’AVVALORAVA
IN ME GUARDANDO, UNA SOLA PARVENZA,
MUTANDOM’ IO, A ME SI TRAVAGLIAVA.114

NE LA PROFONDA E CHIARA SUSSISTENZA
DE L’ALTO LUME PARVERMI TRE GIRI
DI TRE COLORI E D’UNA CONTENENZA;117

E L’UN DA L’ALTRO COME IRI DA IRI
PAREA REFLESSO, E ’L TERZO PAREA FOCO
CHE QUINCI E QUINDI IGUALMENTE SI SPIRI.120

OH QUANTO È CORTO IL DIRE E COME FIOCO
AL MIO CONCETTO! E QUESTO, A QUEL CH’I’ VIDI,
È TANTO, CHE NON BASTA A DICER ’POCO’.123

O LUCE ETTERNA CHE SOLA IN TE SIDI,
SOLA T’INTENDI, E DA TE INTELLETTA
E INTENDENTE TE AMI E ARRIDI!126

QUELLA CIRCULAZION CHE SÌ CONCETTA
PAREVA IN TE COME LUME REFLESSO,
DA LI OCCHI MIEI ALQUANTO CIRCUNSPETTA,129

DENTRO DA SÉ, DEL SUO COLORE STESSO,
MI PARVE PINTA DE LA NOSTRA EFFIGE:
PER CHE ’L MIO VISO IN LEI TUTTO ERA MESSO.132

QUAL È ’L GEOMÈTRA CHE TUTTO S’AFFIGE
PER MISURAR LO CERCHIO, E NON RITROVA,
PENSANDO, QUEL PRINCIPIO OND’ ELLI INDIGE,135

TAL ERA IO A QUELLA VISTA NOVA:
VEDER VOLEVA COME SI CONVENNE
L’IMAGO AL CERCHIO E COME VI S’INDOVA;138

MA NON ERAN DA CIÒ LE PROPRIE PENNE:
SE NON CHE LA MIA MENTE FU PERCOSSA
DA UN FULGORE IN CHE SUA VOGLIA VENNE.141

A L’ALTA FANTASIA QUI MANCÒ POSSA;
MA GIÀ VOLGEVA IL MIO DISIO E ’L VELLE,
SÌ COME ROTA CH’IGUALMENTE È MOSSA,144

L’AMOR CHE MOVE IL SOLE E L’ALTRE STELLE.`,
]

const random = function(max, min) {  
    return Math.floor(Math.random() * (max - min) + min);
}  

const monkey_write = function() {
    let textarea = document.getElementById("monkey-output")
    textarea.innerHTML += characters[random(0, 49)]
    textarea.scrollTop = textarea.scrollHeight;
}


const clear_output = function() {
    document.getElementById("monkey-output").innerHTML = "";
}

const load_text = function(text_id) {
    let output = document.getElementById("monkey-output");
    
    output.innerHTML += "... forse miliardi di anni dopo ..."
    for (let i = 0; i < 52; i++) {
        monkey_write()
    }
    
    output.innerHTML += examples[text_id]
    
    for (let i = 0; i < 24; i++) {
        monkey_write()
    }
}

const update_interval = function(new_value) {
    clearInterval(input_interval)
    // console.log("%O", new_value)

    input_interval = setInterval(monkey_write, timeout_interval / (new_value.target.value / 10))
    // alert(new_value)
}

window.onload = function() {
    const initial_value = document.getElementById("speed").value
    document.getElementById("speed").addEventListener("change", update_interval)
    input_interval = setInterval(monkey_write, timeout_interval / (initial_value / 10))
}